"""外食で食べる料理のレシピ。buildDishes.py が成分表と突き合わせて栄養価を出す。

g は「1人前あたりの可食部の重さ」。
q は成分表の名前に含まれる語をつないだもの（例: '中華めん+ゆで'）。
絞りきれない語はビルド時に候補が出るので、そのとき id で指定し直す。

量は一般的な外食1人前を目安にしている。店による差は大きく、
ラーメンは同じ醤油でも500〜1200kcalの幅がある。目安として扱う。
"""

# よく使う食材。同じ語を何度も書かないための短縮。
RICE = "こめ+［水稲めし］+精白米+うるち米"
SOY = "こいくちしょうゆ"
MISO = "米みそ+淡色辛みそ"
SUGAR = "車糖+上白糖"
OIL = "調合油"
SESAME_OIL = "ごま油"
ONION = "たまねぎ+りん茎+生"
LONG_ONION = "根深ねぎ+葉+軟白+生"
CARROT = "にんじん+根+皮なし+生"
CABBAGE = "キャベツ+結球葉+生"
EGG_RAW = "鶏卵+全卵+生"
EGG_BOILED = "鶏卵+全卵+ゆで"
PORK_LOIN = "ぶた+［大型種肉］+ロース+脂身つき+生"
PORK_BELLY = "ぶた+［大型種肉］+ばら+脂身つき+生"
BEEF_SHOULDER = "うし+［輸入牛肉］+かた+脂身つき+生"
CHICKEN_THIGH = "にわとり+［若どり・主品目］+もも+皮つき+生"
CHAR_SIU = "ぶた+［その他］+焼き豚"
TONKATSU = "ぶた+［大型種肉］+ロース+脂身つき+とんかつ"
SHRIMP_TEMPURA = "バナメイえび+養殖+天ぷら"
NORI = "あまのり+焼きのり"
MENMA = "たけのこ+水煮缶詰"
NARUTO = "＜水産練り製品＞+なると"

# 麺類のスープ。しょうゆ・みそ・塩とだしで作る想定の、飲み干した場合の量。
RAMEN_SOUP_SOY = [
    {"q": SOY, "g": 25},
    {"q": SESAME_OIL, "g": 5},
]
RAMEN_SOUP_MISO = [
    {"q": MISO, "g": 35},
    {"q": SESAME_OIL, "g": 8},
]

MORE_NOODLES = [
    {
        "id": "dish-tantanmen", "name": "担々麺", "category": "麺類",
        "keywords": ["担々麺", "たんたんめん", "タンタンメン"],
        "portions": [{"label": "1杯", "grams": 700}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 220},
            {"q": "ぶた+［ひき肉］+生", "g": 50},
            {"q": "チンゲンサイ+葉+生", "g": 30},
            {"q": "ごま+ねり", "g": 25},
            {"q": SESAME_OIL, "g": 8},
            {"q": SOY, "g": 15},
            {"q": "（辛味調味料類）+トウバンジャン", "g": 5},
            {"water": True, "g": 350, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-champon", "name": "ちゃんぽん", "category": "麺類",
        "keywords": ["ちゃんぽん", "チャンポン"],
        "portions": [{"label": "1杯", "grams": 750}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 230},
            {"q": "ぶた+［大型種肉］+かた+脂身つき+生", "g": 30},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 20},
            {"q": "＜いか・たこ類＞+（いか類）+するめいか+生", "g": 20},
            {"q": CABBAGE, "g": 60},
            {"q": "だいず+もやし+生", "g": 40},
            {"q": CARROT, "g": 15},
            {"q": "＜水産練り製品＞+蒸しかまぼこ", "g": 15},
            {"q": OIL, "g": 8},
            {"q": "食塩+食塩", "g": 2},
            {"water": True, "g": 310, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-abura-soba", "name": "油そば・まぜそば", "category": "麺類",
        "keywords": ["油そば", "まぜそば", "あぶらそば"],
        "portions": [{"label": "1杯", "grams": 380}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 250},
            {"q": CHAR_SIU, "g": 40},
            {"q": MENMA, "g": 25},
            {"q": LONG_ONION, "g": 10},
            {"q": EGG_RAW, "g": 20},
            {"q": SESAME_OIL, "g": 15},
            {"q": SOY, "g": 20},
        ],
    },
    {
        "id": "dish-ankake-yakisoba", "name": "あんかけ焼きそば", "category": "麺類",
        "keywords": ["あんかけ焼きそば", "皿うどん"],
        "portions": [{"label": "1皿", "grams": 400}],
        "recipe": [
            {"q": "中華めん+蒸し中華めん+蒸し中華めん", "g": 180},
            {"q": OIL, "g": 12},
            {"q": "中国料理+菜類+八宝菜", "g": 200},
        ],
    },
    {
        "id": "dish-udon-tsukimi", "name": "月見うどん", "category": "麺類",
        "keywords": ["月見うどん", "つきみうどん"],
        "portions": [{"label": "1杯", "grams": 530}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": EGG_RAW, "g": 55},
            {"q": LONG_ONION, "g": 10},
            {"q": "うすくちしょうゆ", "g": 15},
            {"water": True, "g": 200, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-curry-udon", "name": "カレーうどん", "category": "麺類",
        "keywords": ["カレーうどん", "カレー南蛮"],
        "portions": [{"label": "1杯", "grams": 550}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": "洋風料理+カレー類+ビーフカレー", "g": 150},
            {"q": LONG_ONION, "g": 15},
            {"q": SOY, "g": 10},
            {"water": True, "g": 130, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-nabeyaki-udon", "name": "鍋焼きうどん", "category": "麺類",
        "keywords": ["鍋焼きうどん", "なべやきうどん"],
        "portions": [{"label": "1杯", "grams": 600}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": EGG_RAW, "g": 55},
            {"q": SHRIMP_TEMPURA, "g": 40},
            {"q": "＜水産練り製品＞+蒸しかまぼこ", "g": 20},
            {"q": "生しいたけ+菌床栽培+生", "g": 15},
            {"q": LONG_ONION, "g": 10},
            {"q": "うすくちしょうゆ", "g": 15},
            {"water": True, "g": 195, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-soba-tempura", "name": "天ぷらそば", "category": "麺類",
        "keywords": ["天ぷらそば", "てんぷらそば"],
        "portions": [{"label": "1杯", "grams": 540}],
        "recipe": [
            {"q": "そば+そば+ゆで", "g": 250},
            {"q": SHRIMP_TEMPURA, "g": 45},
            {"q": LONG_ONION, "g": 10},
            {"q": SOY, "g": 15},
            {"water": True, "g": 220, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-somen", "name": "そうめん", "category": "麺類",
        "keywords": ["そうめん", "素麺", "ひやむぎ"],
        "portions": [{"label": "1人前", "grams": 290}],
        "recipe": [
            {"q": "そうめん・ひやむぎ+ゆで", "g": 250},
            {"q": LONG_ONION, "g": 5},
            {"q": SOY, "g": 20},
            {"water": True, "g": 15, "as": "つゆの水"},
        ],
    },
    {
        "id": "dish-pasta-tarako", "name": "スパゲッティ（たらこ）", "category": "麺類",
        "keywords": ["たらこパスタ", "明太子パスタ", "たらこスパゲッティ"],
        "portions": [{"label": "1人前", "grams": 300}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "たらこ+生", "g": 35},
            {"q": "バター+有塩バター", "g": 12},
            {"q": NORI, "g": 1},
        ],
    },
    {
        "id": "dish-pasta-vongole", "name": "スパゲッティ（ボンゴレ）", "category": "麺類",
        "keywords": ["ボンゴレ", "あさりパスタ", "ぼんごれ"],
        "portions": [{"label": "1人前", "grams": 330}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "あさり+生", "g": 60},
            {"q": "オリーブ油", "g": 15},
            {"q": "にんにく+りん茎+生", "g": 5},
        ],
    },
    {
        "id": "dish-pasta-mushroom", "name": "スパゲッティ（きのこ和風）", "category": "麺類",
        "keywords": ["きのこパスタ", "和風パスタ"],
        "portions": [{"label": "1人前", "grams": 340}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "えのきたけ+生", "g": 30},
            {"q": "ぶなしめじ+生", "g": 30},
            {"q": "バター+有塩バター", "g": 10},
            {"q": SOY, "g": 12},
            {"q": NORI, "g": 1},
        ],
    },
    {
        "id": "dish-reimen", "name": "冷麺", "category": "麺類",
        "keywords": ["冷麺", "れいめん", "韓国冷麺"],
        "portions": [{"label": "1杯", "grams": 550}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 220},
            {"q": "うし+［輸入牛肉］+かた+赤肉+生", "g": 30},
            {"q": "きゅうり+果実+生", "g": 30},
            {"q": EGG_BOILED, "g": 25},
            {"q": "はくさい+漬物+キムチ", "g": 30},
            {"q": SOY, "g": 15},
            {"water": True, "g": 200, "as": "スープの水"},
        ],
    },
    {
        "id": "dish-bihun", "name": "焼きビーフン", "category": "麺類",
        "keywords": ["ビーフン", "びーふん", "焼きビーフン"],
        "portions": [{"label": "1皿", "grams": 300}],
        "recipe": [
            {"q": "こめ+［うるち米製品］+ビーフン", "g": 70},
            {"q": "ぶた+［大型種肉］+かた+脂身つき+生", "g": 30},
            {"q": CABBAGE, "g": 50},
            {"q": CARROT, "g": 15},
            {"q": "だいず+もやし+生", "g": 40},
            {"q": OIL, "g": 8},
            {"q": SOY, "g": 12},
            {"water": True, "g": 75, "as": "もどし・蒸しの水"},
        ],
    },
]

MORE_RICE = [
    {
        "id": "dish-tenshinhan", "name": "天津飯", "category": "丼・ごはんもの",
        "keywords": ["天津飯", "てんしんはん", "天津丼"],
        "portions": [{"label": "1杯", "grams": 420}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": EGG_RAW, "g": 110},
            {"q": "たらばがに+水煮缶詰", "g": 25},
            {"q": OIL, "g": 8},
            {"q": SOY, "g": 12},
            {"water": True, "g": 15, "as": "あんの水"},
        ],
    },
    {
        "id": "dish-mabo-don", "name": "麻婆丼", "category": "丼・ごはんもの",
        "keywords": ["麻婆丼", "マーボー丼"],
        "portions": [{"label": "1杯", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "中国料理+菜類+麻婆豆腐", "g": 200},
        ],
    },
    {
        "id": "dish-gapao", "name": "ガパオライス", "category": "丼・ごはんもの",
        "keywords": ["ガパオ", "ガパオライス", "ガパオご飯"],
        "portions": [{"label": "1皿", "grams": 420}],
        "recipe": [
            {"q": RICE, "g": 230},
            {"q": "にわとり+［二次品目］+ひき肉+生", "g": 80},
            {"q": "青ピーマン+果実+生", "g": 25},
            {"q": ONION, "g": 25},
            {"q": EGG_RAW, "g": 50},
            {"q": OIL, "g": 10},
            {"q": "オイスターソース", "g": 12},
        ],
    },
    {
        "id": "dish-bibimbap", "name": "ビビンバ", "category": "丼・ごはんもの",
        "keywords": ["ビビンバ", "びびんば", "石焼きビビンバ"],
        "portions": [{"label": "1杯", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "うし+［輸入牛肉］+かた+赤肉+生", "g": 50},
            {"q": "だいず+もやし+生", "g": 40},
            {"q": "ほうれんそう+葉+通年平均+ゆで", "g": 30},
            {"q": CARROT, "g": 20},
            {"q": "はくさい+漬物+キムチ", "g": 30},
            {"q": EGG_RAW, "g": 25},
            {"q": SESAME_OIL, "g": 8},
            {"q": "（みそ類）+練りみそ", "g": 12},
        ],
    },
    {
        "id": "dish-taco-rice", "name": "タコライス", "category": "丼・ごはんもの",
        "keywords": ["タコライス", "たこらいす"],
        "portions": [{"label": "1皿", "grams": 400}],
        "recipe": [
            {"q": RICE, "g": 230},
            {"q": "うし+［ひき肉］+生", "g": 60},
            {"q": "（レタス類）+レタス+土耕栽培+結球葉+生", "g": 30},
            {"q": "トマト+果実+生", "g": 40},
            {"q": "プロセスチーズ", "g": 20},
            {"q": "トマト加工品類+トマトケチャップ", "g": 20},
        ],
    },
    {
        "id": "dish-unadon", "name": "うな丼", "category": "丼・ごはんもの",
        "keywords": ["うな丼", "うなぎ", "うな重", "鰻丼"],
        "portions": [{"label": "1杯", "grams": 360}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": "うなぎ+かば焼", "g": 80},
            {"q": SOY, "g": 10},
            {"q": SUGAR, "g": 6},
        ],
    },
    {
        "id": "dish-tekka-don", "name": "鉄火丼", "category": "丼・ごはんもの",
        "keywords": ["鉄火丼", "てっかどん", "まぐろ丼"],
        "portions": [{"label": "1杯", "grams": 350}],
        "recipe": [
            {"q": RICE, "g": 240},
            {"q": "まぐろ類+きはだ+生", "g": 90},
            {"q": NORI, "g": 1},
            {"q": SOY, "g": 12},
        ],
    },
    {
        "id": "dish-negitoro-don", "name": "ネギトロ丼", "category": "丼・ごはんもの",
        "keywords": ["ネギトロ丼", "ねぎとろ丼", "ネギトロ"],
        "portions": [{"label": "1杯", "grams": 360}],
        "recipe": [
            {"q": RICE, "g": 240},
            {"q": "まぐろ類+くろまぐろ+養殖+赤身+生", "g": 60},
            {"q": "まぐろ類+くろまぐろ+天然+脂身+生", "g": 30},
            {"q": LONG_ONION, "g": 10},
            {"q": SOY, "g": 12},
        ],
    },
    {
        "id": "dish-shirasu-don", "name": "しらす丼", "category": "丼・ごはんもの",
        "keywords": ["しらす丼", "シラス丼"],
        "portions": [{"label": "1杯", "grams": 310}],
        "recipe": [
            {"q": RICE, "g": 240},
            {"q": "＜魚類＞+しらす干し+微乾燥品", "g": 40},
            {"q": NORI, "g": 1},
            {"q": SOY, "g": 8},
        ],
    },
    {
        "id": "dish-soboro-don", "name": "そぼろ丼", "category": "丼・ごはんもの",
        "keywords": ["そぼろ丼", "三色丼", "鶏そぼろ"],
        "portions": [{"label": "1杯", "grams": 380}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "にわとり+［二次品目］+ひき肉+生", "g": 60},
            {"q": EGG_RAW, "g": 50},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 6},
        ],
    },
    {
        "id": "dish-chirashi", "name": "ちらし寿司", "category": "丼・ごはんもの",
        "keywords": ["ちらし寿司", "ちらしずし", "五目寿司"],
        "portions": [{"label": "1人前", "grams": 350}],
        "recipe": [
            {"q": RICE, "g": 220},
            {"q": "＜調味料類＞+（調味ソース類）+すし酢+ちらし・稲荷用", "g": 20},
            {"q": EGG_RAW, "g": 25},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 20},
            {"q": "＜魚類＞+（さけ・ます類）+しろさけ+イクラ", "g": 15},
            {"q": "きゅうり+果実+生", "g": 20},
            {"q": "生しいたけ+菌床栽培+生", "g": 15},
            {"q": NORI, "g": 1},
        ],
    },
    {
        "id": "dish-makizushi", "name": "巻き寿司（1本）", "category": "丼・ごはんもの",
        "keywords": ["巻き寿司", "巻寿司", "海苔巻き", "太巻き"],
        "portions": [{"label": "1本", "grams": 250}, {"label": "1切れ", "grams": 42}],
        "recipe": [
            {"q": RICE, "g": 170},
            {"q": "＜調味料類＞+（調味ソース類）+すし酢+巻き寿司・箱寿司用", "g": 15},
            {"q": NORI, "g": 3},
            {"q": EGG_RAW, "g": 20},
            {"q": "きゅうり+果実+生", "g": 15},
            {"q": "かんぴょう+甘煮", "g": 12},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 20},
        ],
    },
    {
        "id": "dish-ochazuke", "name": "お茶漬け", "category": "丼・ごはんもの",
        "keywords": ["お茶漬け", "おちゃづけ", "茶漬け"],
        "portions": [{"label": "1杯", "grams": 350}],
        "recipe": [
            {"q": RICE, "g": 180},
            {"q": "さけ・ます類+しろさけ+焼き", "g": 15},
            {"q": NORI, "g": 1},
            {"q": "食塩+食塩", "g": 1},
            {"water": True, "g": 150, "as": "お茶"},
        ],
    },
    {
        "id": "dish-zosui", "name": "雑炊", "category": "丼・ごはんもの",
        "keywords": ["雑炊", "ぞうすい", "おじや"],
        "portions": [{"label": "1杯", "grams": 350}],
        "recipe": [
            {"q": RICE, "g": 150},
            {"q": EGG_RAW, "g": 40},
            {"q": LONG_ONION, "g": 10},
            {"q": SOY, "g": 10},
            {"water": True, "g": 140, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-onigiri-kombu", "name": "おにぎり（昆布）", "category": "丼・ごはんもの",
        "keywords": ["昆布おにぎり", "こんぶおにぎり"],
        "portions": [{"label": "1個", "grams": 110}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "こんぶ+つくだ煮", "g": 10},
            {"q": NORI, "g": 1},
        ],
    },
    {
        "id": "dish-onigiri-okaka", "name": "おにぎり（おかか）", "category": "丼・ごはんもの",
        "keywords": ["おかかおにぎり", "かつおぶしおにぎり"],
        "portions": [{"label": "1個", "grams": 108}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "＜魚類＞+（かつお類）+加工品+削り節", "g": 4},
            {"q": SOY, "g": 4},
            {"q": NORI, "g": 1},
        ],
    },
    {
        "id": "dish-onigiri-mentaiko", "name": "おにぎり（明太子）", "category": "丼・ごはんもの",
        "keywords": ["明太子おにぎり", "めんたいこおにぎり"],
        "portions": [{"label": "1個", "grams": 116}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "たらこ+焼き", "g": 15},
            {"q": NORI, "g": 1},
        ],
    },
]

MORE_WASHOKU = [
    {
        "id": "dish-yakitori", "name": "焼き鳥（もも・タレ2本）", "category": "定食・和食",
        "keywords": ["焼き鳥", "やきとり", "焼鳥"],
        "portions": [{"label": "2本", "grams": 90}, {"label": "1本", "grams": 45}],
        "recipe": [
            {"q": CHICKEN_THIGH, "g": 80},
            {"q": SOY, "g": 8},
            {"q": SUGAR, "g": 4},
        ],
    },
    {
        "id": "dish-yakitori-shio", "name": "焼き鳥（塩2本）", "category": "定食・和食",
        "keywords": ["焼き鳥塩", "やきとり塩"],
        "portions": [{"label": "2本", "grams": 82}],
        "recipe": [
            {"q": CHICKEN_THIGH, "g": 80},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-kushikatsu", "name": "串カツ（3本）", "category": "定食・和食",
        "keywords": ["串カツ", "くしかつ", "串揚げ"],
        "portions": [{"label": "3本", "grams": 120}, {"label": "1本", "grams": 40}],
        "recipe": [
            {"q": TONKATSU, "g": 90},
            {"q": ONION, "g": 20},
            {"q": "ウスターソース類+ウスターソース", "g": 12},
        ],
    },
    {
        "id": "dish-agedashi-tofu", "name": "揚げ出し豆腐", "category": "定食・和食",
        "keywords": ["揚げ出し豆腐", "あげだしどうふ"],
        "portions": [{"label": "1皿", "grams": 200}],
        "recipe": [
            {"q": "だいず+［豆腐・油揚げ類］+木綿豆腐", "g": 150},
            {"q": OIL, "g": 10},
            {"q": SOY, "g": 10},
            {"q": LONG_ONION, "g": 5},
            {"water": True, "g": 25, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-chawanmushi", "name": "茶碗蒸し", "category": "定食・和食",
        "keywords": ["茶碗蒸し", "ちゃわんむし"],
        "portions": [{"label": "1個", "grams": 150}],
        "recipe": [
            {"q": EGG_RAW, "g": 40},
            {"q": "にわとり+［若どり・主品目］+むね+皮なし+生", "g": 15},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 10},
            {"q": "生しいたけ+菌床栽培+生", "g": 8},
            {"q": "うすくちしょうゆ", "g": 5},
            {"water": True, "g": 72, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-oden", "name": "おでん（5種）", "category": "定食・和食",
        "keywords": ["おでん"],
        "portions": [{"label": "1人前", "grams": 330}],
        "recipe": [
            {"q": "だいこん+根+皮なし+ゆで", "g": 80},
            {"q": EGG_BOILED, "g": 50},
            {"q": "こんにゃく+板こんにゃく+精粉こんにゃく", "g": 50},
            {"q": "＜水産練り製品＞+焼き竹輪", "g": 30},
            {"q": "だいず+［豆腐・油揚げ類］+生揚げ", "g": 50},
            {"q": SOY, "g": 12},
            {"water": True, "g": 60, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-sukiyaki", "name": "すき焼き", "category": "定食・和食",
        "keywords": ["すき焼き", "すきやき"],
        "portions": [{"label": "1人前", "grams": 400}],
        "recipe": [
            {"q": "うし+［輸入牛肉］+ばら+脂身つき+生", "g": 120},
            {"q": "だいず+［豆腐・油揚げ類］+焼き豆腐", "g": 80},
            {"q": "しらたき", "g": 60},
            {"q": LONG_ONION, "g": 50},
            {"q": "はくさい+結球葉+生", "g": 50},
            {"q": "生しいたけ+菌床栽培+生", "g": 20},
            {"q": SOY, "g": 25},
            {"q": SUGAR, "g": 12},
        ],
    },
    {
        "id": "dish-shabushabu", "name": "しゃぶしゃぶ", "category": "定食・和食",
        "keywords": ["しゃぶしゃぶ", "しゃぶ"],
        "portions": [{"label": "1人前", "grams": 380}],
        "recipe": [
            {"q": PORK_LOIN, "g": 120},
            {"q": "はくさい+結球葉+生", "g": 100},
            {"q": "だいず+［豆腐・油揚げ類］+木綿豆腐", "g": 80},
            {"q": LONG_ONION, "g": 30},
            {"q": "えのきたけ+生", "g": 30},
            {"q": "＜調味料類＞+（調味ソース類）+ごまだれ", "g": 25},
        ],
    },
    {
        "id": "dish-kimchi-nabe", "name": "キムチ鍋", "category": "定食・和食",
        "keywords": ["キムチ鍋", "きむちなべ", "チゲ"],
        "portions": [{"label": "1人前", "grams": 500}],
        "recipe": [
            {"q": PORK_BELLY, "g": 80},
            {"q": "はくさい+漬物+キムチ", "g": 80},
            {"q": "だいず+［豆腐・油揚げ類］+木綿豆腐", "g": 80},
            {"q": "はくさい+結球葉+生", "g": 80},
            {"q": "だいず+もやし+生", "g": 40},
            {"q": LONG_ONION, "g": 20},
            {"q": MISO, "g": 15},
            {"water": True, "g": 105, "as": "だしの水"},
        ],
    },
    {
        "id": "dish-saba-misoni", "name": "さばの味噌煮", "category": "定食・和食",
        "keywords": ["さばの味噌煮", "鯖の味噌煮", "さば味噌"],
        "portions": [{"label": "1切れ", "grams": 130}],
        "recipe": [
            {"q": "＜魚類＞+（さば類）+まさば+生", "g": 100},
            {"q": MISO, "g": 15},
            {"q": SUGAR, "g": 6},
            {"q": "しょうが+根茎+皮なし+生", "g": 3},
            {"water": True, "g": 6, "as": "煮汁の水"},
        ],
    },
    {
        "id": "dish-buri-teriyaki", "name": "ぶりの照り焼き", "category": "定食・和食",
        "keywords": ["ぶりの照り焼き", "ブリ照り", "照り焼き"],
        "portions": [{"label": "1切れ", "grams": 100}],
        "recipe": [
            {"q": "＜魚類＞+ぶり+成魚+生", "g": 85},
            {"q": SOY, "g": 8},
            {"q": SUGAR, "g": 5},
        ],
    },
    {
        "id": "dish-sashimi", "name": "刺身盛り合わせ", "category": "定食・和食",
        "keywords": ["刺身", "さしみ", "お造り"],
        "portions": [{"label": "1人前", "grams": 130}],
        "recipe": [
            {"q": "まぐろ類+きはだ+生", "g": 40},
            {"q": "さけ・ます類+しろさけ+生", "g": 30},
            {"q": "＜いか・たこ類＞+（いか類）+するめいか+生", "g": 25},
            {"q": "＜魚類＞+（たい類）+まだい+養殖+皮つき+生", "g": 25},
            {"q": SOY, "g": 10},
        ],
    },
    {
        "id": "dish-potato-salad", "name": "ポテトサラダ", "category": "定食・和食",
        "keywords": ["ポテトサラダ", "ポテサラ"],
        "portions": [{"label": "1皿", "grams": 120}],
        "recipe": [
            {"q": "じゃがいも+塊茎+皮なし+蒸し", "g": 80},
            {"q": "きゅうり+果実+生", "g": 15},
            {"q": CARROT, "g": 10},
            {"q": "マヨネーズ+全卵型", "g": 15},
        ],
    },
    {
        "id": "dish-salad-green", "name": "サラダ（野菜のみ）", "category": "定食・和食",
        "keywords": ["サラダ", "野菜サラダ", "グリーンサラダ"],
        "portions": [{"label": "1皿", "grams": 130}],
        "recipe": [
            {"q": "（レタス類）+レタス+土耕栽培+結球葉+生", "g": 50},
            {"q": "トマト+果実+生", "g": 40},
            {"q": "きゅうり+果実+生", "g": 25},
            {"q": "＜調味料類＞+（ドレッシング類）+和風ドレッシングタイプ調味料+ノンオイルタイプ", "g": 15},
        ],
    },
    {
        "id": "dish-caesar-salad", "name": "シーザーサラダ", "category": "定食・和食",
        "keywords": ["シーザーサラダ", "しーざーさらだ"],
        "portions": [{"label": "1皿", "grams": 160}],
        "recipe": [
            {"q": "（レタス類）+レタス+土耕栽培+結球葉+生", "g": 80},
            {"q": "ベーコン類+ばらベーコン", "g": 15},
            {"q": "ナチュラルチーズ+パルメザン", "g": 8},
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 15},
            {"q": "＜調味料類＞+（ドレッシング類）+マヨネーズ+全卵型", "g": 25},
        ],
    },
]

MORE_CHINESE_WESTERN = [
    {
        "id": "dish-hoikoro", "name": "回鍋肉", "category": "洋食・ファストフード",
        "keywords": ["回鍋肉", "ホイコーロー", "ほいこーろー"],
        "portions": [{"label": "1皿", "grams": 250}],
        "recipe": [
            {"q": PORK_BELLY, "g": 80},
            {"q": CABBAGE, "g": 120},
            {"q": "青ピーマン+果実+生", "g": 25},
            {"q": OIL, "g": 8},
            {"q": "テンメンジャン", "g": 15},
            {"q": "（辛味調味料類）+トウバンジャン", "g": 3},
        ],
    },
    {
        "id": "dish-chinjao", "name": "青椒肉絲", "category": "洋食・ファストフード",
        "keywords": ["青椒肉絲", "チンジャオロース", "ちんじゃおろーす"],
        "portions": [{"label": "1皿", "grams": 230}],
        "recipe": [
            {"q": "うし+［輸入牛肉］+かた+赤肉+生", "g": 80},
            {"q": "青ピーマン+果実+生", "g": 60},
            {"q": MENMA, "g": 50},
            {"q": OIL, "g": 10},
            {"q": "オイスターソース", "g": 12},
            {"q": SOY, "g": 8},
        ],
    },
    {
        "id": "dish-ebi-chili", "name": "エビチリ", "category": "洋食・ファストフード",
        "keywords": ["エビチリ", "えびちり", "海老のチリソース"],
        "portions": [{"label": "1皿", "grams": 200}],
        "recipe": [
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 120},
            {"q": ONION, "g": 30},
            {"q": "トマト加工品類+トマトケチャップ", "g": 25},
            {"q": OIL, "g": 10},
            {"q": "（辛味調味料類）+トウバンジャン", "g": 5},
        ],
    },
    {
        "id": "dish-yurinchi", "name": "油淋鶏", "category": "洋食・ファストフード",
        "keywords": ["油淋鶏", "ユーリンチー", "ゆーりんちー"],
        "portions": [{"label": "1皿", "grams": 200}],
        "recipe": [
            {"q": "和風料理+その他+とりから揚げ", "g": 160},
            {"q": LONG_ONION, "g": 20},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 5},
        ],
    },
    {
        "id": "dish-rebanira", "name": "レバニラ炒め", "category": "洋食・ファストフード",
        "keywords": ["レバニラ", "ればにら", "ニラレバ"],
        "portions": [{"label": "1皿", "grams": 230}],
        "recipe": [
            {"q": "にわとり+［副品目］+肝臓+生", "g": 80},
            {"q": "にら+葉+生", "g": 60},
            {"q": "だいず+もやし+生", "g": 60},
            {"q": OIL, "g": 10},
            {"q": SOY, "g": 12},
        ],
    },
    {
        "id": "dish-kanitama", "name": "かに玉", "category": "洋食・ファストフード",
        "keywords": ["かに玉", "カニ玉", "芙蓉蟹"],
        "portions": [{"label": "1皿", "grams": 200}],
        "recipe": [
            {"q": EGG_RAW, "g": 110},
            {"q": "たらばがに+水煮缶詰", "g": 30},
            {"q": LONG_ONION, "g": 15},
            {"q": OIL, "g": 10},
            {"q": SOY, "g": 10},
            {"water": True, "g": 20, "as": "あんの水"},
        ],
    },
    {
        "id": "dish-omelette", "name": "オムレツ（プレーン）", "category": "洋食・ファストフード",
        "keywords": ["オムレツ", "おむれつ"],
        "portions": [{"label": "1個", "grams": 130}],
        "recipe": [
            {"q": EGG_RAW, "g": 110},
            {"q": "バター+有塩バター", "g": 8},
            {"q": "普通牛乳", "g": 10},
            {"q": "食塩+食塩", "g": 0.5},
        ],
    },
    {
        "id": "dish-medamayaki", "name": "目玉焼き", "category": "洋食・ファストフード",
        "keywords": ["目玉焼き", "めだまやき"],
        "portions": [{"label": "1個", "grams": 55}],
        "recipe": [
            {"q": EGG_RAW, "g": 50},
            {"q": OIL, "g": 3},
        ],
    },
    {
        "id": "dish-bacon-egg", "name": "ベーコンエッグ", "category": "洋食・ファストフード",
        "keywords": ["ベーコンエッグ", "ハムエッグ"],
        "portions": [{"label": "1皿", "grams": 95}],
        "recipe": [
            {"q": EGG_RAW, "g": 50},
            {"q": "ベーコン類+ばらベーコン", "g": 35},
            {"q": OIL, "g": 3},
        ],
    },
    {
        "id": "dish-pancake", "name": "パンケーキ（2枚）", "category": "洋食・ファストフード",
        "keywords": ["パンケーキ", "ホットケーキ", "ぱんけーき"],
        "portions": [{"label": "2枚", "grams": 200}],
        "recipe": [
            {"q": "＜ケーキ・ペストリー類＞+ホットケーキ", "g": 160},
            {"q": "バター+有塩バター", "g": 10},
            {"q": "メープルシロップ", "g": 30},
        ],
    },
    {
        "id": "dish-french-toast", "name": "フレンチトースト", "category": "洋食・ファストフード",
        "keywords": ["フレンチトースト", "ふれんちとーすと"],
        "portions": [{"label": "1枚", "grams": 130}],
        "recipe": [
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 60},
            {"q": EGG_RAW, "g": 30},
            {"q": "普通牛乳", "g": 30},
            {"q": SUGAR, "g": 8},
            {"q": "バター+有塩バター", "g": 8},
        ],
    },
    {
        "id": "dish-pizza-toast", "name": "ピザトースト", "category": "洋食・ファストフード",
        "keywords": ["ピザトースト", "ぴざとーすと"],
        "portions": [{"label": "1枚", "grams": 130}],
        "recipe": [
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 60},
            {"q": "プロセスチーズ", "g": 30},
            {"q": "トマト加工品類+トマトケチャップ", "g": 15},
            {"q": "ソーセージ類+ウインナーソーセージ+ウインナーソーセージ", "g": 20},
            {"q": "青ピーマン+果実+生", "g": 8},
        ],
    },
    {
        "id": "dish-katsu-sando", "name": "カツサンド", "category": "洋食・ファストフード",
        "keywords": ["カツサンド", "かつサンド"],
        "portions": [{"label": "1パック", "grams": 200}],
        "recipe": [
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 80},
            {"q": TONKATSU, "g": 90},
            {"q": "ウスターソース類+中濃ソース", "g": 15},
            {"q": CABBAGE, "g": 15},
        ],
    },
    {
        "id": "dish-tamago-sando", "name": "たまごサンド", "category": "洋食・ファストフード",
        "keywords": ["たまごサンド", "玉子サンド", "卵サンド"],
        "portions": [{"label": "1パック", "grams": 160}],
        "recipe": [
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 80},
            {"q": EGG_BOILED, "g": 60},
            {"q": "マヨネーズ+全卵型", "g": 20},
        ],
    },
    {
        "id": "dish-yakisoba-pan", "name": "焼きそばパン", "category": "洋食・ファストフード",
        "keywords": ["焼きそばパン", "やきそばパン"],
        "portions": [{"label": "1個", "grams": 160}],
        "recipe": [
            {"q": "こむぎ+［パン類］+コッペパン+コッペパン", "g": 70},
            {"q": "中華めん+蒸し中華めん+蒸し中華めん", "g": 70},
            {"q": "ウスターソース類+中濃ソース", "g": 12},
            {"q": CABBAGE, "g": 15},
        ],
    },
    {
        "id": "dish-curry-pan", "name": "カレーパン", "category": "洋食・ファストフード",
        "keywords": ["カレーパン", "かれーぱん"],
        "portions": [{"label": "1個", "grams": 120}],
        "recipe": [
            {"q": "＜菓子パン類＞+カレーパン+皮及び具", "g": 120},
        ],
    },
    {
        "id": "dish-melon-pan", "name": "メロンパン", "category": "洋食・ファストフード",
        "keywords": ["メロンパン", "めろんぱん"],
        "portions": [{"label": "1個", "grams": 90}],
        "recipe": [
            {"q": "＜菓子パン類＞+メロンパン", "g": 90},
        ],
    },
    {
        "id": "dish-anpan", "name": "あんぱん", "category": "洋食・ファストフード",
        "keywords": ["あんぱん", "あんパン"],
        "portions": [{"label": "1個", "grams": 90}],
        "recipe": [
            {"q": "＜菓子パン類＞+あんパン+こしあん入り", "g": 90},
        ],
    },
    {
        "id": "dish-croissant", "name": "クロワッサン", "category": "洋食・ファストフード",
        "keywords": ["クロワッサン", "くろわっさん"],
        "portions": [{"label": "1個", "grams": 45}],
        "recipe": [
            {"q": "こむぎ+［パン類］+クロワッサン+レギュラータイプ", "g": 45},
        ],
    },
    {
        "id": "dish-teriyaki-burger", "name": "てりやきバーガー", "category": "洋食・ファストフード",
        "keywords": ["てりやきバーガー", "テリヤキバーガー", "照り焼きバーガー"],
        "portions": [{"label": "1個", "grams": 140}],
        "recipe": [
            {"q": "こむぎ+［パン類］+バンズ", "g": 50},
            {"q": "ぶた+［ひき肉］+生", "g": 45},
            {"q": "マヨネーズ+全卵型", "g": 15},
            {"q": SOY, "g": 8},
            {"q": SUGAR, "g": 4},
            {"q": "（レタス類）+レタス+土耕栽培+結球葉+生", "g": 10},
        ],
    },
    {
        "id": "dish-fish-burger", "name": "フィッシュバーガー", "category": "洋食・ファストフード",
        "keywords": ["フィッシュバーガー", "フィレオフィッシュ"],
        "portions": [{"label": "1個", "grams": 130}],
        "recipe": [
            {"q": "こむぎ+［パン類］+バンズ", "g": 50},
            {"q": "洋風料理+フライ類+白身フライ", "g": 55},
            {"q": "プロセスチーズ", "g": 10},
            {"q": "マヨネーズ+全卵型", "g": 12},
        ],
    },
    {
        "id": "dish-fried-chicken", "name": "フライドチキン（1ピース）", "category": "洋食・ファストフード",
        "keywords": ["フライドチキン", "ケンタッキー", "チキン"],
        "portions": [{"label": "1ピース", "grams": 90}],
        "recipe": [
            {"q": "和風料理+その他+とりから揚げ", "g": 90},
        ],
    },
    {
        "id": "dish-clam-chowder", "name": "クラムチャウダー", "category": "洋食・ファストフード",
        "keywords": ["クラムチャウダー", "くらむちゃうだー"],
        "portions": [{"label": "1杯", "grams": 220}],
        "recipe": [
            {"q": "あさり+缶詰+水煮", "g": 25},
            {"q": "じゃがいも+塊茎+皮なし+生", "g": 40},
            {"q": ONION, "g": 25},
            {"q": "普通牛乳", "g": 100},
            {"q": "クリーム+乳脂肪", "g": 20},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-minestrone", "name": "ミネストローネ", "category": "洋食・ファストフード",
        "keywords": ["ミネストローネ", "みねすとろーね"],
        "portions": [{"label": "1杯", "grams": 220}],
        "recipe": [
            {"q": "（トマト類）+加工品+ホール+食塩無添加", "g": 70},
            {"q": ONION, "g": 30},
            {"q": CARROT, "g": 20},
            {"q": "セロリ+葉柄+生", "g": 15},
            {"q": "ベーコン類+ばらベーコン", "g": 10},
            {"q": "オリーブ油", "g": 5},
            {"q": "食塩+食塩", "g": 1},
            {"water": True, "g": 69, "as": "スープの水"},
        ],
    },
    {
        "id": "dish-roll-cabbage", "name": "ロールキャベツ", "category": "洋食・ファストフード",
        "keywords": ["ロールキャベツ", "ろーるきゃべつ"],
        "portions": [{"label": "2個", "grams": 250}],
        "recipe": [
            {"q": CABBAGE, "g": 120},
            {"q": "うし+［ひき肉］+生", "g": 70},
            {"q": ONION, "g": 25},
            {"q": "＜調味料類＞+（だし類）+固形ブイヨン", "g": 3},
            {"water": True, "g": 32, "as": "煮汁の水"},
        ],
    },
]

DISHES = [
    # ── 麺類 ──────────────────────────────────────────────
    {
        "id": "dish-ramen-shoyu",
        "name": "ラーメン（醤油・スープを飲む）",
        "category": "麺類",
        "keywords": ["ラーメン", "らーめん", "醤油ラーメン", "中華そば"],
        "portions": [{"label": "1杯", "grams": 700}, {"label": "大盛", "grams": 900}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 230},
            {"q": CHAR_SIU, "g": 40},
            {"q": MENMA, "g": 20},
            {"q": LONG_ONION, "g": 10},
            {"q": NARUTO, "g": 10},
            {"q": EGG_BOILED, "g": 25},
            *RAMEN_SOUP_SOY,
            {"water": True, "g": 335, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-ramen-shoyu-nosoup",
        "name": "ラーメン（醤油・スープを残す）",
        "category": "麺類",
        "keywords": ["ラーメンスープ残す", "らーめんすーぷのこす"],
        "portions": [{"label": "1杯", "grams": 340}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 230},
            {"q": CHAR_SIU, "g": 40},
            {"q": MENMA, "g": 20},
            {"q": LONG_ONION, "g": 10},
            {"q": NARUTO, "g": 10},
            {"q": EGG_BOILED, "g": 25},
            # スープに溶けた塩分・脂の一部だけが麺に残る
            {"q": SOY, "g": 8},
            {"q": SESAME_OIL, "g": 2},
        ],
    },
    {
        "id": "dish-ramen-miso",
        "name": "味噌ラーメン",
        "category": "麺類",
        "keywords": ["味噌ラーメン", "みそラーメン", "みそらーめん"],
        "portions": [{"label": "1杯", "grams": 750}, {"label": "大盛", "grams": 950}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 230},
            {"q": "ぶた+［ひき肉］+生", "g": 30},
            {"q": "だいず+もやし+生", "g": 40},
            {"q": CABBAGE, "g": 30},
            {"q": "スイートコーン+未熟種子+カーネル+冷凍", "g": 20},
            {"q": "バター+有塩バター", "g": 5},
            *RAMEN_SOUP_MISO,
            {"water": True, "g": 352, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-ramen-tonkotsu",
        "name": "豚骨ラーメン",
        "category": "麺類",
        "keywords": ["豚骨ラーメン", "とんこつラーメン", "とんこつらーめん"],
        "portions": [{"label": "1杯", "grams": 700}, {"label": "替玉あり", "grams": 830}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 200},
            {"q": CHAR_SIU, "g": 45},
            {"q": "きくらげ+ゆで", "g": 10},
            {"q": LONG_ONION, "g": 10},
            {"q": EGG_BOILED, "g": 25},
            # 白湯スープは脂とゼラチンが多い
            {"q": PORK_BELLY, "g": 20},
            {"q": SOY, "g": 15},
            {"water": True, "g": 375, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-tsukemen",
        "name": "つけ麺",
        "category": "麺類",
        "keywords": ["つけ麺", "つけめん"],
        "portions": [{"label": "1人前", "grams": 500}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 300},
            {"q": CHAR_SIU, "g": 40},
            {"q": MENMA, "g": 25},
            {"q": EGG_BOILED, "g": 25},
            {"q": SOY, "g": 20},
            {"q": SESAME_OIL, "g": 6},
            {"water": True, "g": 84, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-udon-kake",
        "name": "かけうどん",
        "category": "麺類",
        "keywords": ["かけうどん", "うどん"],
        "portions": [{"label": "1杯", "grams": 480}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": LONG_ONION, "g": 10},
            {"q": "うすくちしょうゆ", "g": 15},
            {"water": True, "g": 205, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-udon-kitsune",
        "name": "きつねうどん",
        "category": "麺類",
        "keywords": ["きつねうどん", "きつね"],
        "portions": [{"label": "1杯", "grams": 510}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": "油揚げ+味付け", "g": 25},
            {"q": LONG_ONION, "g": 10},
            {"q": "うすくちしょうゆ", "g": 15},
            {"water": True, "g": 210, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-udon-tempura",
        "name": "天ぷらうどん",
        "category": "麺類",
        "keywords": ["天ぷらうどん", "天ぷらそば", "てんぷらうどん"],
        "portions": [{"label": "1杯", "grams": 540}],
        "recipe": [
            {"q": "うどん+ゆで", "g": 250},
            {"q": SHRIMP_TEMPURA, "g": 45},
            {"q": LONG_ONION, "g": 10},
            {"q": "うすくちしょうゆ", "g": 15},
            {"water": True, "g": 220, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-soba-kake",
        "name": "かけそば",
        "category": "麺類",
        "keywords": ["かけそば", "そば", "蕎麦"],
        "portions": [{"label": "1杯", "grams": 480}],
        "recipe": [
            {"q": "そば+そば+ゆで", "g": 250},
            {"q": LONG_ONION, "g": 10},
            {"q": SOY, "g": 15},
            {"water": True, "g": 205, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-soba-zaru",
        "name": "ざるそば",
        "category": "麺類",
        "keywords": ["ざるそば", "もりそば", "ざる蕎麦"],
        "portions": [{"label": "1人前", "grams": 290}],
        "recipe": [
            {"q": "そば+そば+ゆで", "g": 260},
            {"q": NORI, "g": 1},
            {"q": SOY, "g": 20},
            {"water": True, "g": 9, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-yakisoba",
        "name": "焼きそば",
        "category": "麺類",
        "keywords": ["焼きそば", "やきそば"],
        "portions": [{"label": "1人前", "grams": 350}],
        "recipe": [
            {"q": "中華めん+蒸し中華めん+蒸し中華めん", "g": 200},
            {"q": PORK_BELLY, "g": 30},
            {"q": CABBAGE, "g": 60},
            {"q": ONION, "g": 20},
            {"q": CARROT, "g": 10},
            {"q": OIL, "g": 8},
            {"q": "ウスターソース類+中濃ソース", "g": 25},
        ],
    },
    {
        "id": "dish-pasta-meat",
        "name": "スパゲッティ（ミートソース）",
        "category": "麺類",
        "keywords": ["ミートソース", "パスタ", "スパゲッティ", "ボロネーゼ"],
        "portions": [{"label": "1人前", "grams": 420}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "うし+［ひき肉］+生", "g": 50},
            {"q": "（トマト類）+加工品+ホール+食塩無添加", "g": 80},
            {"q": ONION, "g": 30},
            {"q": OIL, "g": 8},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-pasta-carbonara",
        "name": "スパゲッティ（カルボナーラ）",
        "category": "麺類",
        "keywords": ["カルボナーラ", "かるぼなーら"],
        "portions": [{"label": "1人前", "grams": 400}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "ベーコン類+ばらベーコン", "g": 40},
            {"q": "クリーム+乳脂肪", "g": 60},
            {"q": EGG_RAW, "g": 30},
            {"q": "ナチュラルチーズ+パルメザン", "g": 15},
        ],
    },
    {
        "id": "dish-pasta-peperoncino",
        "name": "スパゲッティ（ペペロンチーノ）",
        "category": "麺類",
        "keywords": ["ペペロンチーノ", "ぺぺろんちーの"],
        "portions": [{"label": "1人前", "grams": 290}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "オリーブ油", "g": 20},
            {"q": "にんにく+りん茎+生", "g": 8},
            {"q": "とうがらし+果実+乾", "g": 1},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-pasta-napolitan",
        "name": "スパゲッティ（ナポリタン）",
        "category": "麺類",
        "keywords": ["ナポリタン", "なぽりたん"],
        "portions": [{"label": "1人前", "grams": 400}],
        "recipe": [
            {"q": "マカロニ・スパゲッティ+ゆで", "g": 250},
            {"q": "ソーセージ類+ウインナーソーセージ+ウインナーソーセージ", "g": 40},
            {"q": ONION, "g": 40},
            {"q": "青ピーマン+果実+生", "g": 20},
            {"q": "トマト加工品類+トマトケチャップ", "g": 45},
            {"q": OIL, "g": 8},
        ],
    },
    {
        "id": "dish-hiyashi-chuka",
        "name": "冷やし中華",
        "category": "麺類",
        "keywords": ["冷やし中華", "ひやしちゅうか"],
        "portions": [{"label": "1人前", "grams": 420}],
        "recipe": [
            {"q": "中華めん+ゆで", "g": 230},
            {"q": "きゅうり+果実+生", "g": 40},
            {"q": "ハム類+ロースハム+ロースハム", "g": 30},
            {"q": EGG_RAW, "g": 30},
            {"q": "トマト+果実+生", "g": 40},
            {"q": SOY, "g": 20},
            {"q": SESAME_OIL, "g": 5},
        ],
    },

    # ── 丼・ごはんもの ─────────────────────────────────────
    {
        "id": "dish-gyudon",
        "name": "牛丼",
        "category": "丼・ごはんもの",
        "keywords": ["牛丼", "ぎゅうどん"],
        "portions": [
            {"label": "並盛", "grams": 350},
            {"label": "大盛", "grams": 450},
            {"label": "特盛", "grams": 550},
        ],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": "うし+［輸入牛肉］+ばら+脂身つき+生", "g": 70},
            {"q": ONION, "g": 30},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 5},
        ],
    },
    {
        "id": "dish-butadon",
        "name": "豚丼",
        "category": "丼・ごはんもの",
        "keywords": ["豚丼", "ぶたどん"],
        "portions": [{"label": "並盛", "grams": 350}, {"label": "大盛", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": PORK_LOIN, "g": 70},
            {"q": ONION, "g": 20},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 5},
        ],
    },
    {
        "id": "dish-oyakodon",
        "name": "親子丼",
        "category": "丼・ごはんもの",
        "keywords": ["親子丼", "おやこどん"],
        "portions": [{"label": "1杯", "grams": 420}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": CHICKEN_THIGH, "g": 70},
            {"q": EGG_RAW, "g": 55},
            {"q": ONION, "g": 30},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 4},
        ],
    },
    {
        "id": "dish-katsudon",
        "name": "カツ丼",
        "category": "丼・ごはんもの",
        "keywords": ["カツ丼", "かつ丼", "かつどん"],
        "portions": [{"label": "1杯", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": TONKATSU, "g": 110},
            {"q": EGG_RAW, "g": 50},
            {"q": ONION, "g": 30},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 4},
        ],
    },
    {
        "id": "dish-tendon",
        "name": "天丼",
        "category": "丼・ごはんもの",
        "keywords": ["天丼", "てんどん"],
        "portions": [{"label": "1杯", "grams": 420}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": SHRIMP_TEMPURA, "g": 60},
            {"q": "さつまいも+塊根+皮つき+天ぷら", "g": 40},
            {"q": SOY, "g": 12},
            {"q": SUGAR, "g": 5},
        ],
    },
    {
        "id": "dish-kaisendon",
        "name": "海鮮丼",
        "category": "丼・ごはんもの",
        "keywords": ["海鮮丼", "かいせんどん"],
        "portions": [{"label": "1杯", "grams": 400}],
        "recipe": [
            {"q": RICE, "g": 240},
            {"q": "まぐろ類+きはだ+生", "g": 40},
            {"q": "さけ・ます類+しろさけ+生", "g": 30},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 25},
            {"q": "＜いか・たこ類＞+（いか類）+するめいか+生", "g": 25},
            {"q": SOY, "g": 12},
        ],
    },
    {
        "id": "dish-chukadon",
        "name": "中華丼",
        "category": "丼・ごはんもの",
        "keywords": ["中華丼", "ちゅうかどん"],
        "portions": [{"label": "1杯", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 260},
            {"q": "中国料理+菜類+八宝菜", "g": 180},
        ],
    },
    {
        "id": "dish-curry-rice",
        "name": "カレーライス",
        "category": "丼・ごはんもの",
        "keywords": ["カレーライス", "カレー", "かれー"],
        "portions": [{"label": "1皿", "grams": 450}, {"label": "大盛", "grams": 570}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "洋風料理+カレー類+ビーフカレー", "g": 200},
        ],
    },
    {
        "id": "dish-katsu-curry",
        "name": "カツカレー",
        "category": "丼・ごはんもの",
        "keywords": ["カツカレー", "かつカレー"],
        "portions": [{"label": "1皿", "grams": 560}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "洋風料理+カレー類+ビーフカレー", "g": 200},
            {"q": TONKATSU, "g": 110},
        ],
    },
    {
        "id": "dish-omurice",
        "name": "オムライス",
        "category": "丼・ごはんもの",
        "keywords": ["オムライス", "おむらいす"],
        "portions": [{"label": "1皿", "grams": 400}],
        "recipe": [
            {"q": RICE, "g": 230},
            {"q": EGG_RAW, "g": 100},
            {"q": "にわとり+［若どり・主品目］+むね+皮なし+生", "g": 40},
            {"q": ONION, "g": 25},
            {"q": "トマト加工品類+トマトケチャップ", "g": 40},
            {"q": "バター+有塩バター", "g": 10},
        ],
    },
    {
        "id": "dish-hayashi-rice",
        "name": "ハヤシライス",
        "category": "丼・ごはんもの",
        "keywords": ["ハヤシライス", "はやしらいす"],
        "portions": [{"label": "1皿", "grams": 450}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "洋風料理+シチュー類+ビーフシチュー", "g": 200},
        ],
    },
    {
        "id": "dish-sushi-nigiri",
        "name": "にぎり寿司（10貫）",
        "category": "丼・ごはんもの",
        "keywords": ["寿司", "すし", "にぎり", "握り寿司"],
        "portions": [{"label": "10貫", "grams": 350}, {"label": "1貫", "grams": 35}],
        "recipe": [
            {"q": RICE, "g": 200},
            {"q": "＜調味料類＞+（調味ソース類）+すし酢+にぎり用", "g": 20},
            {"q": "まぐろ類+きはだ+生", "g": 30},
            {"q": "さけ・ます類+しろさけ+生", "g": 25},
            {"q": "＜えび・かに類＞+（えび類）+バナメイえび+養殖+生", "g": 20},
            {"q": "＜いか・たこ類＞+（いか類）+するめいか+生", "g": 20},
            {"q": "＜貝類＞+ほたてがい+貝柱+生", "g": 20},
            {"q": "＜魚類＞+（さば類）+まさば+生", "g": 15},
        ],
    },
    {
        "id": "dish-inari",
        "name": "いなり寿司（2個）",
        "category": "丼・ごはんもの",
        "keywords": ["いなり寿司", "いなり", "稲荷寿司"],
        "portions": [{"label": "2個", "grams": 140}, {"label": "1個", "grams": 70}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "＜調味料類＞+（調味ソース類）+すし酢+ちらし・稲荷用", "g": 10},
            {"q": "油揚げ+味付け", "g": 30},
        ],
    },
    {
        "id": "dish-onigiri-salmon",
        "name": "おにぎり（鮭）",
        "category": "丼・ごはんもの",
        "keywords": ["おにぎり", "鮭おにぎり", "おむすび"],
        "portions": [{"label": "1個", "grams": 110}, {"label": "2個", "grams": 220}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "さけ・ます類+しろさけ+焼き", "g": 8},
            {"q": NORI, "g": 1},
            {"q": "食塩+食塩", "g": 0.5},
        ],
    },
    {
        "id": "dish-onigiri-tuna",
        "name": "おにぎり（ツナマヨ）",
        "category": "丼・ごはんもの",
        "keywords": ["ツナマヨおにぎり", "ツナマヨ"],
        "portions": [{"label": "1個", "grams": 120}, {"label": "2個", "grams": 240}],
        "recipe": [
            {"q": RICE, "g": 100},
            {"q": "まぐろ類+缶詰+水煮+フレーク+ライト", "g": 15},
            {"q": "マヨネーズ+全卵型", "g": 8},
            {"q": NORI, "g": 1},
        ],
    },

    # ── 定食・和食 ────────────────────────────────────────
    {
        "id": "dish-teishoku-yakizakana",
        "name": "焼き魚定食",
        "category": "定食・和食",
        "keywords": ["焼き魚定食", "焼魚定食", "さば定食"],
        "portions": [{"label": "1食", "grams": 500}],
        "recipe": [
            {"q": RICE, "g": 200},
            {"q": "＜魚類＞+（さば類）+まさば+焼き", "g": 100},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
            {"q": "（だいこん類）+漬物+たくあん漬+塩押しだいこん漬", "g": 20},
            {"q": SOY, "g": 6},
        ],
    },
    {
        "id": "dish-teishoku-karaage",
        "name": "唐揚げ定食",
        "category": "定食・和食",
        "keywords": ["唐揚げ定食", "からあげ定食", "から揚げ定食"],
        "portions": [{"label": "1食", "grams": 560}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "和風料理+その他+とりから揚げ", "g": 140},
            {"q": CABBAGE, "g": 50},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
        ],
    },
    {
        "id": "dish-teishoku-shogayaki",
        "name": "生姜焼き定食",
        "category": "定食・和食",
        "keywords": ["生姜焼き定食", "しょうが焼き定食", "生姜焼き"],
        "portions": [{"label": "1食", "grams": 560}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": PORK_LOIN, "g": 120},
            {"q": ONION, "g": 30},
            {"q": SOY, "g": 15},
            {"q": SUGAR, "g": 5},
            {"q": OIL, "g": 8},
            {"q": CABBAGE, "g": 50},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
        ],
    },
    {
        "id": "dish-teishoku-tonkatsu",
        "name": "とんかつ定食",
        "category": "定食・和食",
        "keywords": ["とんかつ定食", "トンカツ定食", "豚カツ定食"],
        "portions": [{"label": "1食", "grams": 590}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": TONKATSU, "g": 130},
            {"q": CABBAGE, "g": 60},
            {"q": "ウスターソース類+中濃ソース", "g": 15},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
        ],
    },
    {
        "id": "dish-teishoku-tempura",
        "name": "天ぷら定食",
        "category": "定食・和食",
        "keywords": ["天ぷら定食", "てんぷら定食"],
        "portions": [{"label": "1食", "grams": 560}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": SHRIMP_TEMPURA, "g": 60},
            {"q": "さつまいも+塊根+皮つき+天ぷら", "g": 40},
            {"q": "なす+果実+天ぷら", "g": 30},
            {"q": SOY, "g": 15},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
        ],
    },
    {
        "id": "dish-teishoku-hamburg",
        "name": "ハンバーグ定食",
        "category": "定食・和食",
        "keywords": ["ハンバーグ定食", "はんばーぐ定食"],
        "portions": [{"label": "1食", "grams": 590}],
        "recipe": [
            {"q": RICE, "g": 250},
            {"q": "洋風料理+ハンバーグステーキ類+合いびきハンバーグ", "g": 150},
            {"q": "ウスターソース類+中濃ソース", "g": 20},
            {"q": CABBAGE, "g": 40},
            {"q": "和風料理+汁物類+とん汁", "g": 150},
        ],
    },
    {
        "id": "dish-misoshiru",
        "name": "味噌汁",
        "category": "定食・和食",
        "keywords": ["味噌汁", "みそ汁", "みそしる"],
        "portions": [{"label": "1杯", "grams": 180}],
        "recipe": [
            {"q": MISO, "g": 12},
            {"q": "だいず+［豆腐・油揚げ類］+絹ごし豆腐", "g": 30},
            {"q": "わかめ+原藻+生", "g": 5},
            {"q": LONG_ONION, "g": 5},
            {"water": True, "g": 128, "as": "だし・スープの水"},
        ],
    },
    {
        "id": "dish-hiyayakko",
        "name": "冷奴",
        "category": "定食・和食",
        "keywords": ["冷奴", "ひややっこ"],
        "portions": [{"label": "1皿", "grams": 160}],
        "recipe": [
            {"q": "だいず+［豆腐・油揚げ類］+絹ごし豆腐", "g": 150},
            {"q": SOY, "g": 8},
            {"q": LONG_ONION, "g": 3},
        ],
    },
    {
        "id": "dish-dashimaki",
        "name": "だし巻き卵",
        "category": "定食・和食",
        "keywords": ["だし巻き卵", "だし巻き", "卵焼き", "玉子焼き"],
        "portions": [{"label": "1皿", "grams": 120}],
        "recipe": [
            {"q": EGG_RAW, "g": 110},
            {"q": "うすくちしょうゆ", "g": 5},
            {"q": SUGAR, "g": 3},
            {"q": OIL, "g": 4},
        ],
    },
    {
        "id": "dish-edamame",
        "name": "枝豆",
        "category": "定食・和食",
        "keywords": ["枝豆", "えだまめ"],
        "portions": [{"label": "1皿", "grams": 80}],
        "recipe": [
            {"q": "えだまめ+ゆで", "g": 80},
            {"q": "食塩+食塩", "g": 0.5},
        ],
    },

    # ── 洋食・ファストフード ──────────────────────────────
    {
        "id": "dish-hamburger",
        "name": "ハンバーガー",
        "category": "洋食・ファストフード",
        "keywords": ["ハンバーガー", "はんばーがー", "バーガー"],
        "portions": [{"label": "1個", "grams": 110}],
        "recipe": [
            {"q": "こむぎ+［パン類］+バンズ", "g": 50},
            {"q": "うし+［ひき肉］+生", "g": 45},
            {"q": ONION, "g": 8},
            {"q": "トマト加工品類+トマトケチャップ", "g": 8},
        ],
    },
    {
        "id": "dish-cheeseburger",
        "name": "チーズバーガー",
        "category": "洋食・ファストフード",
        "keywords": ["チーズバーガー", "ちーずばーがー"],
        "portions": [{"label": "1個", "grams": 130}],
        "recipe": [
            {"q": "こむぎ+［パン類］+バンズ", "g": 50},
            {"q": "うし+［ひき肉］+生", "g": 45},
            {"q": "プロセスチーズ", "g": 18},
            {"q": ONION, "g": 8},
            {"q": "トマト加工品類+トマトケチャップ", "g": 8},
        ],
    },
    {
        "id": "dish-french-fries",
        "name": "フライドポテト（M）",
        "category": "洋食・ファストフード",
        "keywords": ["フライドポテト", "ポテト", "ふらいどぽてと"],
        "portions": [{"label": "Mサイズ", "grams": 135}, {"label": "Sサイズ", "grams": 75}],
        "recipe": [
            {"id": "02020", "g": 135, "as": "フライドポテト（市販冷凍食品を揚げたもの）"},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-chicken-nugget",
        "name": "チキンナゲット（5個）",
        "category": "洋食・ファストフード",
        "keywords": ["ナゲット", "チキンナゲット"],
        "portions": [{"label": "5個", "grams": 95}, {"label": "1個", "grams": 19}],
        "recipe": [
            {"q": "＜鳥肉類＞+［その他］+チキンナゲット", "g": 95},
        ],
    },
    {
        "id": "dish-pizza-margherita",
        "name": "ピザ（マルゲリータ・1枚）",
        "category": "洋食・ファストフード",
        "keywords": ["ピザ", "ぴざ", "マルゲリータ", "ピッツァ"],
        "portions": [{"label": "1枚", "grams": 300}, {"label": "1切れ", "grams": 50}],
        "recipe": [
            {"q": "こむぎ+［その他］+ピザ生地", "g": 180},
            {"q": "（トマト類）+加工品+ホール+食塩無添加", "g": 50},
            {"q": "ナチュラルチーズ+モッツァレラ", "g": 60},
            {"q": "オリーブ油", "g": 8},
        ],
    },
    {
        "id": "dish-steak",
        "name": "ステーキ（サーロイン）",
        "category": "洋食・ファストフード",
        "keywords": ["ステーキ", "すてーき", "サーロイン"],
        "portions": [{"label": "1枚", "grams": 200}],
        "recipe": [
            {"q": "うし+［輸入牛肉］+サーロイン+脂身つき+生", "g": 180},
            {"q": "バター+有塩バター", "g": 8},
            {"q": "食塩+食塩", "g": 1},
        ],
    },
    {
        "id": "dish-doria",
        "name": "ドリア",
        "category": "洋食・ファストフード",
        "keywords": ["ドリア", "どりあ"],
        "portions": [{"label": "1皿", "grams": 400}],
        "recipe": [
            {"q": RICE, "g": 200},
            {"q": "洋風料理+その他+えびグラタン", "g": 180},
            {"q": "バター+有塩バター", "g": 8},
        ],
    },
    {
        "id": "dish-sandwich",
        "name": "サンドイッチ（ハムたまご）",
        "category": "洋食・ファストフード",
        "keywords": ["サンドイッチ", "さんどいっち", "サンド"],
        "portions": [{"label": "1パック", "grams": 180}],
        "recipe": [
            {"q": "こむぎ+［パン類］+角形食パン+食パン", "g": 90},
            {"q": "ハム類+ロースハム+ロースハム", "g": 25},
            {"q": EGG_BOILED, "g": 40},
            {"q": "マヨネーズ+全卵型", "g": 15},
            {"q": "（レタス類）+レタス+土耕栽培+結球葉+生", "g": 10},
        ],
    },
    {
        "id": "dish-hotdog",
        "name": "ホットドッグ",
        "category": "洋食・ファストフード",
        "keywords": ["ホットドッグ", "ほっとどっぐ"],
        "portions": [{"label": "1個", "grams": 120}],
        "recipe": [
            {"q": "こむぎ+［パン類］+コッペパン+コッペパン", "g": 60},
            {"q": "ソーセージ類+ウインナーソーセージ+ウインナーソーセージ", "g": 45},
            {"q": "トマト加工品類+トマトケチャップ", "g": 12},
        ],
    },
    *MORE_NOODLES,
    *MORE_RICE,
    *MORE_WASHOKU,
    *MORE_CHINESE_WESTERN,
]
